services:
  - type: web
    name: speakup
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput
    startCommand: gunicorn SpeakUp.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DJANGO_SETTINGS_MODULE
        value: SpeakUp.settings.production
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        fromService:
          type: web
          name: speakup
          property: host
      - key: DATABASE_URL
        fromDatabase:
          name: speakup-db
          property: connectionString
      - key: CSRF_TRUSTED_ORIGINS
        fromService:
          type: web
          name: speakup
          property: host
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GOOGLE_SITE_VERIFICATION
        sync: false
      - key: FACEBOOK_PIXEL_ID
        sync: false
      - key: GA_MEASUREMENT_ID
        sync: false
    healthCheckPath: /

databases:
  - name: speakup-db
    plan: starter
    databaseName: speakup
    user: speakup

